### ISSUE TITLE
factor bytecode emission out of Externals

### ISSUE THREAD

**Issue by rmuir** [elastic/Painless#17]
there is a lot of tracking here for loads and stores, but it also controls the emission of the bytecodes too. 

it would be great to do some refactoring here so that writer just writes :)

**Comment by jdconrad** [comment]
I agree that external is too confusing...

So here's what I'd like to do as far as some refactoring improvements:

1) Move logic out of external into the respective locations in analyzer and writer.
2) Move logic out of caster into the respective locations in analyzer and writer.
3) Move constant logic into the writer instead of the analyzer to aid with consistency. 
4) Re-evaluate the language definition and seeing if some of the logic can be replaced with using ASM type.

I'll move 2 3 and 4 into separate issues.

**Comment by jdconrad** [comment]
This task is close by #27 .  Forgot to put closes in the log.
